In [35]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'brand':         ['Toyota', 'honda', 'BMW', ' Ford ', 'toyota', 'Honda', 'BMW', 'ford'],
    'year':          [2015, 2018, 2016, None, 2015, 2018, 2016, 2019],
    'mileage':       ['15000 km', '22000 km', None, '18000 km', '15000 km', '22000 km', None, '31000 km'],
    'fuel_type':     ['Petrol', 'Diesel', 'Petrol', 'Diesel', 'Petrol', 'Diesel', 'Petrol', None],
    'selling_price': [500000, 750000, 1200000, None, 500000, 750000, 1200000, 430000]
})

In [36]:
df

    brand    year   mileage fuel_type  selling_price
0  Toyota  2015.0  15000 km    Petrol       500000.0
1   honda  2018.0  22000 km    Diesel       750000.0
2     BMW  2016.0      None    Petrol      1200000.0
3   Ford      NaN  18000 km    Diesel            NaN
4  toyota  2015.0  15000 km    Petrol       500000.0
5   Honda  2018.0  22000 km    Diesel       750000.0
6     BMW  2016.0      None    Petrol      1200000.0
7    ford  2019.0  31000 km      None       430000.0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8 non-null      object
 1   year           7 non-null      float64
 2   mileage        6 non-null      object
 3   fuel_type      7 non-null      object
 4   selling_price  7 non-null      float64
dtypes: float64(2), object(3)
memory usage: 452.0+ bytes

In [38]:
df.describe()

              year  selling_price
count     7.000000   7.000000e+00
mean   2016.714286   7.614286e+05
std       1.603567   3.244189e+05
min    2015.000000   4.300000e+05
25%    2015.500000   5.000000e+05
50%    2016.000000   7.500000e+05
75%    2018.000000   9.750000e+05
max    2019.000000   1.200000e+06

In [39]:
df.shape

(8, 5)

In [40]:
df

    brand    year   mileage fuel_type  selling_price
0  Toyota  2015.0  15000 km    Petrol       500000.0
1   honda  2018.0  22000 km    Diesel       750000.0
2     BMW  2016.0      None    Petrol      1200000.0
3   Ford      NaN  18000 km    Diesel            NaN
4  toyota  2015.0  15000 km    Petrol       500000.0
5   Honda  2018.0  22000 km    Diesel       750000.0
6     BMW  2016.0      None    Petrol      1200000.0
7    ford  2019.0  31000 km      None       430000.0

1.Brand column has a unique values with same brand, need to fix that.
2.year coumn is in float value
3.missing values are there in fuel type and in targer column selling_price.

In [44]:
df.dropna(subset = ['selling_price'], inplace=True)

In [45]:
df['year'].fillna(df['year'].median(),inplace=True)
df['fuel_type'].fillna(df['fuel_type'].mode()[0],inplace=True)

In [46]:
df

    brand    year   mileage fuel_type  selling_price
0  Toyota  2015.0  15000 km    Petrol       500000.0
1   honda  2018.0  22000 km    Diesel       750000.0
2     BMW  2016.0      None    Petrol      1200000.0
4  toyota  2015.0  15000 km    Petrol       500000.0
5   Honda  2018.0  22000 km    Diesel       750000.0
6     BMW  2016.0      None    Petrol      1200000.0
7    ford  2019.0  31000 km    Petrol       430000.0

In [47]:
df['brand'] = df['brand'].str.strip().str.lower()

In [48]:
df

    brand    year   mileage fuel_type  selling_price
0  toyota  2015.0  15000 km    Petrol       500000.0
1   honda  2018.0  22000 km    Diesel       750000.0
2     bmw  2016.0      None    Petrol      1200000.0
4  toyota  2015.0  15000 km    Petrol       500000.0
5   honda  2018.0  22000 km    Diesel       750000.0
6     bmw  2016.0      None    Petrol      1200000.0
7    ford  2019.0  31000 km    Petrol       430000.0

In [49]:
df['mileage'] = df['mileage'].str.extract(r'(\d+)')
df['mileage'] = pd.to_numeric(df['mileage'])

In [50]:
df

    brand    year  mileage fuel_type  selling_price
0  toyota  2015.0  15000.0    Petrol       500000.0
1   honda  2018.0  22000.0    Diesel       750000.0
2     bmw  2016.0      NaN    Petrol      1200000.0
4  toyota  2015.0  15000.0    Petrol       500000.0
5   honda  2018.0  22000.0    Diesel       750000.0
6     bmw  2016.0      NaN    Petrol      1200000.0
7    ford  2019.0  31000.0    Petrol       430000.0

In [51]:
df['mileage'].fillna(df['mileage'].mean(),inplace=True)

In [60]:
df.reset_index()

   index   brand    year  mileage fuel_type  selling_price
0      0  toyota 2015.00 15000.00    Petrol      500000.00
1      1   honda 2018.00 22000.00    Diesel      750000.00
2      2     bmw 2016.00 21000.00    Petrol     1200000.00
3      4  toyota 2015.00 15000.00    Petrol      500000.00
4      5   honda 2018.00 22000.00    Diesel      750000.00
5      6     bmw 2016.00 21000.00    Petrol     1200000.00
6      7    ford 2019.00 31000.00    Petrol      430000.00

In [54]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [55]:
df.describe()

         year  mileage  selling_price
count    7.00     7.00           7.00
mean  2016.71 21000.00      761428.57
std      1.60  5385.16      324418.89
min   2015.00 15000.00      430000.00
25%   2015.50 18000.00      500000.00
50%   2016.00 21000.00      750000.00
75%   2018.00 22000.00      975000.00
max   2019.00 31000.00     1200000.00

In [61]:
df['year'] = df['year'].astype(int)

In [62]:
df

    brand  year  mileage fuel_type  selling_price
0  toyota  2015 15000.00    Petrol      500000.00
1   honda  2018 22000.00    Diesel      750000.00
2     bmw  2016 21000.00    Petrol     1200000.00
4  toyota  2015 15000.00    Petrol      500000.00
5   honda  2018 22000.00    Diesel      750000.00
6     bmw  2016 21000.00    Petrol     1200000.00
7    ford  2019 31000.00    Petrol      430000.00

In [64]:
df.drop_duplicates(inplace=True)

In [65]:
df

    brand  year  mileage fuel_type  selling_price
0  toyota  2015 15000.00    Petrol      500000.00
1   honda  2018 22000.00    Diesel      750000.00
2     bmw  2016 21000.00    Petrol     1200000.00
7    ford  2019 31000.00    Petrol      430000.00

baseline prediction

In [ ]:
sp_mean = df['selling_price'].mean()
sp_mean

720000.0

In [74]:
sp_arr = np.array(df['selling_price'])
sp_arr

array([ 500000.,  750000., 1200000.,  430000.])

In [92]:
mae1 = sp_arr - sp_mean
abs(mae1)

array([220000.,  30000., 480000., 290000.])

In [87]:
baseline = abs(mae1).mean()

In [88]:
baseline

255000.0

In [89]:
predictions = [sp_mean] * len(df)
predictions

[720000.0, 720000.0, 720000.0, 720000.0]

In [ ]:
#using sklearn metric
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(df['selling_price'], predictions)
mae

255000.0