In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [3]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [4]:
df['age'].fillna(df['age'].median(),inplace=True)

In [5]:
df['city'].fillna(df['city'].mode()[0],inplace=True)

In [6]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [7]:
df.drop_duplicates()

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [10]:
pd.get_dummies(df, columns=['city'])

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000        True        False
3            4  35.0    Male         120000       False         True
4            2  35.0  Female          80000        True        False
5            5  40.0    Male          95000        True        False

In [16]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])

In [14]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai       1          40000
1            2  35.0   Delhi       0          80000
2            3  35.0   Delhi       0          60000
3            4  35.0  Mumbai       1         120000
4            2  35.0   Delhi       0          80000
5            5  40.0   Delhi       1          95000

In [19]:
scaler = MinMaxScaler()
df[['age','annual_income']] = scaler.fit_transform(df[['age','annual_income']])
df

   customer_id       age    city  gender  annual_income
0            1  0.000000  Mumbai       1         0.0000
1            2  0.666667   Delhi       0         0.5000
2            3  0.666667   Delhi       0         0.2500
3            4  0.666667  Mumbai       1         1.0000
4            2  0.666667   Delhi       0         0.5000
5            5  1.000000   Delhi       1         0.6875

In [20]:
scaler = StandardScaler()
df[['age','annual_income']] = scaler.fit_transform(df[['age','annual_income']])
df

   customer_id       age    city  gender  annual_income
0            1 -2.042649  Mumbai       1      -1.552077
1            2  0.185695   Delhi       0       0.033023
2            3  0.185695   Delhi       0      -0.759527
3            4  0.185695  Mumbai       1       1.618123
4            2  0.185695   Delhi       0       0.033023
5            5  1.299867   Delhi       1       0.627435

I USE STANDARD SCALER WHEN DATASET HAVING OUTLIERS OR USING LOGISTIC REGRESSION, LINEAR REGRESSION OR SVM

I USER MIN MAX SCALING WHEN DATASET HAVING NO EXTREME OUTLIERS OR USING KNN