In [2]:
import sqlite3

conn = sqlite3.connect("employees.db")

In [3]:
cursor = conn.cursor()

In [3]:
cursor.execute(""" CREATE TABLE IF NOT EXISTS Employees(emp_id INTEGER PRIMARY KEY,name TEXT,department TEXT,salary REAL,years_experience INTEGER,performance_score REAL)""")

In [4]:
import random
Employees_data = []

departments = ['Sales', 'HR', 'Marketing', 'Finance', 'Engineering']

for i in range(1,41):
    name = f"Employee{i}"
    department = random.choice(departments)
    salary = round(random.uniform(50000,15000),2)
    years_experience = random.randint(1,15)
    performance_score = round(random.uniform(1.0,5.0),2)

    Employees_data.append((i, name, department, salary, years_experience, performance_score))

print(Employees_data)

[(1, 'Employee1', 'HR', 20477.01, 7, 4.58), (2, 'Employee2', 'Marketing', 37198.37, 4, 2.89), (3, 'Employee3', 'Marketing', 21262.56, 4, 4.5), (4, 'Employee4', 'Sales', 47533.5, 7, 4.19), (5, 'Employee5', 'Engineering', 26780.97, 13, 3.13), (6, 'Employee6', 'Sales', 22077.37, 10, 2.82), (7, 'Employee7', 'Marketing', 16568.27, 15, 3.37), (8, 'Employee8', 'Finance', 19317.81, 7, 1.71), (9, 'Employee9', 'Finance', 49599.36, 13, 4.85), (10, 'Employee10', 'HR', 40939.36, 13, 3.28), (11, 'Employee11', 'Finance', 17979.06, 1, 4.08), (12, 'Employee12', 'HR', 30446.44, 12, 3.36), (13, 'Employee13', 'Finance', 46996.17, 8, 1.87), (14, 'Employee14', 'Finance', 31883.39, 4, 4.47), (15, 'Employee15', 'Finance', 29782.25, 15, 4.85), (16, 'Employee16', 'Finance', 48337.77, 13, 3.69), (17, 'Employee17', 'Sales', 41288.69, 13, 4.61), (18, 'Employee18', 'Sales', 37273.32, 5, 3.88), (19, 'Employee19', 'Sales', 20197.0, 7, 3.59), (20, 'Employee20', 'Engineering', 43576.07, 13, 1.66), (21, 'Employee21', 'Marketing', 45581.5, 14, 4.55), (22, 'Employee22', 'HR', 22901.26, 9, 1.67), (23, 'Employee23', 'Engineering', 24013.77, 11, 3.6), (24, 'Employee24', 'Finance', 41151.76, 15, 3.25), (25, 'Employee25', 'Sales', 38575.4, 6, 4.64), (26, 'Employee26', 'HR', 49562.17, 10, 4.48), (27, 'Employee27', 'Finance', 29309.75, 9, 1.27), (28, 'Employee28', 'Sales', 28957.32, 13, 1.38), (29, 'Employee29', 'Engineering', 20606.12, 3, 1.4), (30, 'Employee30', 'Engineering', 43999.6, 1, 1.43), (31, 'Employee31', 'HR', 48072.18, 2, 4.57), (32, 'Employee32', 'Marketing', 37772.54, 11, 3.17), (33, 'Employee33', 'Marketing', 21467.54, 6, 2.51), (34, 'Employee34', 'Finance', 26255.06, 9, 1.26), (35, 'Employee35', 'Marketing', 47433.83, 1, 1.09), (36, 'Employee36', 'HR', 22149.42, 13, 3.6), (37, 'Employee37', 'Engineering', 17906.56, 11, 1.74), (38, 'Employee38', 'Finance', 34008.04, 7, 2.95), (39, 'Employee39', 'Marketing', 16471.6, 9, 1.52), (40, 'Employee40', 'Marketing', 37514.59, 11, 1.76)]

In [5]:
cursor.executemany(''' INSERT INTO Employees(empy_id, name, department, salary, years_experience, performance_score) VALUES(?,?,?,?,?,?) ''', Employees_data)

In [5]:
for row in cursor.execute('SELECT * FROM  Employees'):
    print(row)

(1, 'Employee1', 'Engineering', 26664.63, 11, 2.12)
(2, 'Employee2', 'Finance', 23065.59, 14, 3.68)
(3, 'Employee3', 'Finance', 33498.57, 1, 1.59)
(4, 'Employee4', 'Sales', 40224.57, 11, 1.63)
(5, 'Employee5', 'HR', 39764.43, 5, 1.53)
(6, 'Employee6', 'Finance', 29594.87, 5, 4.32)
(7, 'Employee7', 'Finance', 25487.76, 1, 4.74)
(8, 'Employee8', 'Engineering', 36298.14, 11, 2.95)
(9, 'Employee9', 'Finance', 32407.69, 5, 1.94)
(10, 'Employee10', 'Marketing', 26981.72, 15, 3.34)
(11, 'Employee11', 'Marketing', 18863.98, 4, 3.01)
(12, 'Employee12', 'Engineering', 21700.64, 5, 3.26)
(13, 'Employee13', 'HR', 44676.46, 2, 2.9)
(14, 'Employee14', 'HR', 47095.83, 1, 1.5)
(15, 'Employee15', 'HR', 40312.24, 5, 2.28)
(16, 'Employee16', 'Sales', 19667.6, 2, 1.59)
(17, 'Employee17', 'HR', 26770.11, 12, 4.23)
(18, 'Employee18', 'Sales', 47284.74, 9, 4.75)
(19, 'Employee19', 'Marketing', 43393.69, 13, 2.38)
(20, 'Employee20', 'Marketing', 38885.44, 9, 4.36)
(21, 'Employee21', 'HR', 34527.74, 9, 3.96)
(22, 'Employee22', 'Sales', 42402.95, 6, 4.9)
(23, 'Employee23', 'Sales', 24548.01, 9, 2.82)
(24, 'Employee24', 'Finance', 45164.8, 15, 2.04)
(25, 'Employee25', 'Finance', 32605.39, 4, 1.41)
(26, 'Employee26', 'Engineering', 27910.08, 4, 2.86)
(27, 'Employee27', 'HR', 45866.28, 15, 1.02)
(28, 'Employee28', 'Finance', 40922.48, 6, 3.37)
(29, 'Employee29', 'Sales', 42379.72, 14, 3.42)
(30, 'Employee30', 'Sales', 44203.16, 2, 1.44)
(31, 'Employee31', 'HR', 23433.22, 14, 1.09)
(32, 'Employee32', 'HR', 26895.97, 15, 3.5)
(33, 'Employee33', 'Finance', 32111.17, 7, 4.32)
(34, 'Employee34', 'Finance', 21747.09, 11, 4.87)
(35, 'Employee35', 'Marketing', 47128.85, 11, 3.46)
(36, 'Employee36', 'Marketing', 48981.74, 8, 4.39)
(37, 'Employee37', 'Finance', 34065.38, 8, 4.4)
(38, 'Employee38', 'HR', 45456.4, 6, 2.5)
(39, 'Employee39', 'Sales', 21222.49, 6, 3.0)
(40, 'Employee40', 'HR', 39301.89, 1, 4.84)

In [7]:
conn.commit()

In [8]:
conn.close()

In [6]:
import pandas as pd
query = 'SELECT name,department,salary,performance_score from Employees where performance_score >= 4.0 AND years_experience >= 3 ORDER BY performance_score DESC LIMIT 15'
df1 = pd.read_sql(query, conn)
df1

         name department    salary  performance_score
0  Employee22      Sales  42402.95               4.90
1  Employee34    Finance  21747.09               4.87
2  Employee18      Sales  47284.74               4.75
3  Employee37    Finance  34065.38               4.40
4  Employee36  Marketing  48981.74               4.39
5  Employee20  Marketing  38885.44               4.36
6   Employee6    Finance  29594.87               4.32
7  Employee33    Finance  32111.17               4.32
8  Employee17         HR  26770.11               4.23

In [7]:
query = 'SELECT * FROM Employees'
emp_df = pd.read_sql(query, conn)
emp_df

,empy_id,name,department,salary,years_experience,performance_score
0,1,Employee1,Engineering,26664.63,11,2.12
1,2,Employee2,Finance,23065.59,14,3.68
2,3,Employee3,Finance,33498.57,1,1.59
3,4,Employee4,Sales,40224.57,11,1.63
4,5,Employee5,HR,39764.43,5,1.53
5,6,Employee6,Finance,29594.87,5,4.32
6,7,Employee7,Finance,25487.76,1,4.74
7,8,Employee8,Engineering,36298.14,11,2.95
8,9,Employee9,Finance,32407.69,5,1.94
9,10,Employee10,Marketing,26981.72,15,3.34
10,11,Employee11,Marketing,18863.98,4,3.01
11,12,Employee12,Engineering,21700.64,5,3.26
12,13,Employee13,HR,44676.46,2,2.90
13,14,Employee14,HR,47095.83,1,1.50
14,15,Employee15,HR,40312.24,5,2.28
15,16,Employee16,Sales,19667.60,2,1.59
16,17,Employee17,HR,26770.11,12,4.23
17,18,Employee18,Sales,47284.74,9,4.75
18,19,Employee19,Marketing,43393.69,13,2.38
19,20,Employee20,Marketing,38885.44,9,4.36
20,21,Employee21,HR,34527.74,9,3.96
21,22,Employee22,Sales,42402.95,6,4.90
22,23,Employee23,Sales,24548.01,9,2.82
23,24,Employee24,Finance,45164.80,15,2.04
24,25,Employee25,Finance,32605.39,4,1.41
25,26,Employee26,Engineering,27910.08,4,2.86
26,27,Employee27,HR,45866.28,15,1.02
27,28,Employee28,Finance,40922.48,6,3.37
28,29,Employee29,Sales,42379.72,14,3.42
29,30,Employee30,Sales,44203.16,2,1.44
30,31,Employee31,HR,23433.22,14,1.09
31,32,Employee32,HR,26895.97,15,3.50
32,33,Employee33,Finance,32111.17,7,4.32
33,34,Employee34,Finance,21747.09,11,4.87
34,35,Employee35,Marketing,47128.85,11,3.46
35,36,Employee36,Marketing,48981.74,8,4.39
36,37,Employee37,Finance,34065.38,8,4.40
37,38,Employee38,HR,45456.40,6,2.50
38,39,Employee39,Sales,21222.49,6,3.00
39,40,Employee40,HR,39301.89,1,4.84

In [23]:
query = ''' SELECT * from Employees where salary BETWEEN 10000 AND 110000 AND department IN ('Engineering','Sales') ORDER BY department, salary DESC'''
df2 = pd.read_sql(query, conn)
print(df2)

    empy_id        name   department    salary  years_experience  \
0         8   Employee8  Engineering  36298.14                11
1        26  Employee26  Engineering  27910.08                 4
2         1   Employee1  Engineering  26664.63                11
3        12  Employee12  Engineering  21700.64                 5
4        18  Employee18        Sales  47284.74                 9
5        30  Employee30        Sales  44203.16                 2
6        22  Employee22        Sales  42402.95                 6
7        29  Employee29        Sales  42379.72                14
8         4   Employee4        Sales  40224.57                11
9        23  Employee23        Sales  24548.01                 9
10       39  Employee39        Sales  21222.49                 6
11       16  Employee16        Sales  19667.60                 2

    performance_score
0                2.95
1                2.86
2                2.12
3                3.26
4                4.75
5                1.44
6                4.90
7                3.42
8                1.63
9                2.82
10               3.00
11               1.59

In [26]:
query = ''' SELECT 
    department,
    COUNT(*) AS employee_count,
    AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC '''

df3 = pd.read_sql(query, conn)
df3

    department  employee_count    avg_salary
0           HR              11  37645.506364
1    Marketing               6  37372.570000
2        Sales               8  35241.655000
3      Finance              11  31879.162727
4  Engineering               4  28143.372500

In [9]:
avg_perf = emp_df.groupby("department")["performance_score"].mean()

print(avg_perf)

department
Engineering    2.797500
Finance        3.334545
HR             2.668182
Marketing      3.490000
Sales          2.943750
Name: performance_score, dtype: float64

In [13]:
result = emp_df.loc[
    (emp_df["performance_score"] >= 4.0) &
    (emp_df["years_experience"] >= 3),
    ["name","department","salary","performance_score"]
].sort_values(
    by="performance_score",
    ascending=False
).head(15)

print(result)

          name department    salary  performance_score
21  Employee22      Sales  42402.95               4.90
33  Employee34    Finance  21747.09               4.87
17  Employee18      Sales  47284.74               4.75
36  Employee37    Finance  34065.38               4.40
35  Employee36  Marketing  48981.74               4.39
19  Employee20  Marketing  38885.44               4.36
5    Employee6    Finance  29594.87               4.32
32  Employee33    Finance  32111.17               4.32
16  Employee17         HR  26770.11               4.23

SQL and Pandas are both powerful tools for working with structured data, but they differ in syntax and typical use cases. SQL is a declarative language designed specifically for querying relational databases. Its syntax uses operators like =, AND, and ORDER BY to filter and sort data. For example, filtering conditions in SQL use AND between clauses, while Pandas uses & between boolean expressions. Similarly, sorting in SQL uses ORDER BY, whereas Pandas uses the .sort_values() method.

Pandas operates inside Python and uses DataFrames to manipulate data. Conditions are written using Python-style comparisons like == and combined using & or |. Pandas is excellent for exploratory analysis, feature engineering, and integrating data manipulation with machine learning workflows.

SQL is typically used when data is stored in databases and you want to retrieve or aggregate information efficiently. It is optimized to process large datasets directly inside the database engine. Pandas is best suited for in-memory analysis when the dataset can fit into system RAM.

For datasets that are too large to fit in memory, SQL is generally the better choice. Databases process data on disk and use indexing, query optimization, and distributed systems to handle very large datasets efficiently without loading everything into memory.